project/urls.py
"""URLs for the membersystem"""
from django.contrib import admin
from django.urls import include
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index),
    path("users/", include("users.urls")),
    path('admin/', admin.site.urls),
]

users/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.SignupView.as_view(), name='signup'),
    path('signup/confirm/', views.SignupConfirmView.as_view(), name='signup_confirm'),

    path('login/', auth_views.LoginView.as_view(template_name="users/login.html"), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name="users/logged_out.html"), name='logout'),

    path('password_change/', views.PasswordChangeView.as_view(template_name="users/password_change_form.html"), name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name="users/password_change_done.html"), name='password_change_done'),

    path('password_reset/', views.PasswordResetView.as_view(template_name="users/password_reset_form.html"), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name="users/password_reset_done.html"), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(template_name="users/password_reset_confirm.html"), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name="users/password_reset_complete.html"), name='password_reset_complete'),
]

project/views.py
from django.shortcuts import render_to_response


def index(request):
    return render_to_response("index.html")

project/templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <title>{% block head_title %}{% endblock %} – {{ site.name }}</title>
        {% block extra_head %}{% endblock %}
        <link rel="stylesheet" href="{% static '/css/membersystem.css' %}" type="text/css" />
    </head>
    <body>
        <header>
            <h1>
                <a href="/">{{ site.name }}</a>
            </h1>
            <ul>
                {% if user.is_authenticated %}
                    <li><a href="{% url 'users:email' %}">Change e-mail</a></li>
                    <li><a href="{% url 'users:logout' %}">Sign out</a></li>
                {% else %}
                    <li><a href="{% url 'users:login' %}">Sign in</a></li>
                    <li><a href="{% url 'users:signup' %}">Sign up</a></li>
                {% endif %}
            </ul>
        </header>
        {% block body %}
            {% if messages %}
                <ul id="messages">
                    {% for message in messages %}
                        <li>{{message}}</li>
                    {% endfor %}
                </ul>
            {% endif %}

            {% block content %}
            {% endblock %}
        {% endblock %}
        {% block extra_body %}
        {% endblock %}
        <footer>
            <ul>
                <li>
                    <a href="https://data.coop">data.coop</a>
                </li>
                <li>
                    <a href="https://git.data.coop/data.coop/membersystem">source code</a>
                </li>
            </ul>
        </footer>
    </body>
</html>

project/templates/index.html
{% extends "base.html" %}